apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-storage-class
provisioner: kubernetes.io/aws-ebs  # Change according to your cloud provider
parameters:
  type: gp2  # Example parameter for AWS EBS
reclaimPolicy: Delete  # Policy for PV deletion when PVC is deleted